using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;

namespace DrillSergeant.Generators;

[Generator]
public class VerbGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Uncomment the following line to debug the generator.
        // System.Diagnostics.Debugger.Launch();

        var files = context.AdditionalTextsProvider.Where(t => new FileInfo(t.Path).Name.ToLower() == "verbdefinitions.txt");
        var providers = files.Select((text, token) => text.GetText(token)!.ToString());

        context.RegisterSourceOutput(providers, static (context, text) =>
        {
            foreach (var verbGroup in VerbDefinitionParser.Parse(text))
            {
                var ns = $"DrillSergeant.Extensions.{verbGroup.Name}";

                context.AddSource($"{verbGroup.Name}.g.cs", GetVerbGroupStaticsTemplateHeader("DrillSergeant", verbGroup.Name));

                foreach (var verb in verbGroup.Verbs)
                {
                    context.AddSource($"{verbGroup.Name}/{verb}Step.g.cs", GetVerbStepTemplate(ns, verb));
                    context.AddSource($"{verbGroup.Name}/{verb}LambdaStep.g.cs", GetLambdaVerbStepTemplate(ns, verb));
                    context.AddSource($"{verbGroup.Name}/BehaviorExtensions.{verb}.g.cs", GetBehaviorExtensionsTemplate(ns, verb));

                    context.AddSource($"{verbGroup.Name}_{verb}.g.cs", GetVerbGroupStaticsTemplate("DrillSergeant", verbGroup.Name, verb));
                }
            }
        });
    }

    [ExcludeFromCodeCoverage]
    private static string GetVerbStepTemplate(string ns, string verb) => $@"
// <auto-generated />
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace {ns};

[ExcludeFromCodeCoverage]
public class {verb}Step : VerbStep
{{
    public {verb}Step()
    {{
    }}

    public {verb}Step(string? name)
        : base(name)
    {{
    }}

    public override string Verb => ""{verb}"";
}}";

    [ExcludeFromCodeCoverage]
    private static string GetLambdaVerbStepTemplate(string ns, string verb) => $@"
// <auto-generated />
using System.Diagnostics.CodeAnalysis;

namespace {ns};

[ExcludeFromCodeCoverage]
public class {verb}LambdaStep : LambdaStep
{{
    public {verb}LambdaStep()
    {{
        SetVerb(""{verb}"");
    }}

    public {verb}LambdaStep(string name)
        : base(name)
    {{
        SetVerb(""{verb}"");
    }}
}}
";

    [ExcludeFromCodeCoverage]
    private static string GetBehaviorExtensionsTemplate(string ns, string verb) => $@"
// <auto-generated />
using System.Diagnostics.CodeAnalysis;
using System;
using System.Threading.Tasks;

namespace {ns};

[ExcludeFromCodeCoverage]
public static partial class BehaviorExtensions_{verb}
{{
    public static Behavior {verb}(this Behavior behavior, Action step) =>
        behavior.{verb}(step.Method.Name, step);

    public static Behavior {verb}(this Behavior behavior, Action<dynamic> step) =>
        behavior.{verb}(step.Method.Name, step);

    public static Behavior {verb}(this Behavior behavior, Action<dynamic, dynamic> step) =>
        behavior.{verb}(step.Method.Name, step);

    public static Behavior {verb}<TContext>(this Behavior behavior, Action<TContext> step) =>
        behavior.{verb}(step.Method.Name, step);

    public static Behavior {verb}<TInput>(this Behavior behavior, Action<dynamic, TInput> step) =>
        behavior.{verb}(step.Method.Name, step);

    public static Behavior {verb}<TContext, TInput>(this Behavior behavior, Action<TContext, TInput> step) =>
        behavior.{verb}(step.Method.Name, step);

    // ---

    public static Behavior {verb}Async(this Behavior behavior, Func<Task> step) =>
        behavior.{verb}Internal(step.Method.Name, step);

    public static Behavior {verb}Async(this Behavior behavior, Func<dynamic, Task> step) =>
        behavior.{verb}Internal(step.Method.Name, step);

    public static Behavior {verb}Async(this Behavior behavior, Func<dynamic, dynamic, Task> step) =>
        behavior.{verb}Internal(step.Method.Name, step);

    public static Behavior {verb}Async<TContext>(this Behavior behavior, Func<TContext, Task> step) =>
        behavior.{verb}Internal(step.Method.Name, step);

    public static Behavior {verb}Async<TInput>(this Behavior behavior, Func<dynamic, TInput, Task> step) =>
        behavior.{verb}Internal(step.Method.Name, step);

    public static Behavior {verb}Async<TContext, TInput>(this Behavior behavior, Func<TContext, TInput, Task> step) =>
        behavior.{verb}Internal(step.Method.Name, step);

    // ---

    public static Behavior {verb}(this Behavior behavior, string name, Action step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}(this Behavior behavior, string name, Action<dynamic> step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}(this Behavior behavior, string name, Action<dynamic, dynamic> step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}<TContext>(this Behavior behavior, string name, Action<TContext> step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}<TInput>(this Behavior behavior, string name, Action<dynamic, TInput> step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}<TContext, TInput>(this Behavior behavior, string name, Action<TContext, TInput> step) =>
        behavior.{verb}Internal(name, step);

    // ---

    public static Behavior {verb}Async(this Behavior behavior, string name, Func<Task> step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}Async(this Behavior behavior, string name, Func<dynamic, Task> step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}Async(this Behavior behavior, string name, Func<dynamic, dynamic, Task> step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}Async<TContext>(this Behavior behavior, string name, Func<TContext, Task> step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}Async<TInput>(this Behavior behavior, string name, Func<dynamic, TInput, Task> step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}Async<TContext, TInput>(this Behavior behavior, string name, Func<TContext, TInput, Task> step) =>
        behavior.{verb}Internal(name, step);

    // ---

    public static Behavior {verb}<TStep>(this Behavior behavior) where TStep : IStep, new() =>
        behavior.{verb}(new TStep());

    public static Behavior {verb}(this Behavior behavior, IStep step)
    {{
        if(step is LambdaStep lambda)
        {{
            lambda.SetVerb(""{verb}"");
        }}

        behavior.AddStep(step);
        return behavior;
    }}

    // ---

    private static Behavior {verb}Internal(this Behavior behavior, string name, Delegate step)
    {{
        behavior.AddStep(
            new {verb}LambdaStep()
                .SetName(name)
                .Handle(step));

        return behavior;
    }}
}}
";


    [ExcludeFromCodeCoverage]
    private static string GetVerbGroupStaticsTemplateHeader(string ns, string groupName) => $@"
// <auto-generated />
using System.Diagnostics.CodeAnalysis;
using System;
using System.Threading.Tasks;

namespace {ns};

[ExcludeFromCodeCoverage]
public static partial class {groupName}
{{
}}
";


    [ExcludeFromCodeCoverage]
    private static string GetVerbGroupStaticsTemplate(string ns, string groupName, string verb) => $@"
// <auto-generated />
using System.Diagnostics.CodeAnalysis;
using System;
using System.Threading.Tasks;
using DrillSergeant.Extensions.{groupName};

namespace {ns};

public static partial class {groupName}
{{
    public static void {verb}(Action step) =>
        BehaviorBuilder.Current.{verb}(step.Method.Name, step);

    public static void {verb}(Action<dynamic> step) =>
        BehaviorBuilder.Current.{verb}(step.Method.Name, step);

    public static void {verb}(Action<dynamic, dynamic> step) =>
        BehaviorBuilder.Current.{verb}(step.Method.Name, step);

    public static void {verb}<TContext>(Action<TContext> step) =>
        BehaviorBuilder.Current.{verb}(step.Method.Name, step);

    public static void {verb}<TInput>(Action<dynamic, TInput> step) =>
        BehaviorBuilder.Current.{verb}(step.Method.Name, step);

    public static void {verb}<TContext, TInput>(Action<TContext, TInput> step) =>
        BehaviorBuilder.Current.{verb}(step.Method.Name, step);

    // ---

    public static void {verb}Async(Func<Task> step) =>
        BehaviorBuilder.Current.{verb}Async(step.Method.Name, step);

    public static void {verb}Async(Func<dynamic, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(step.Method.Name, step);

    public static void {verb}Async(Func<dynamic, dynamic, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(step.Method.Name, step);

    public static void {verb}Async<TContext>(Func<TContext, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(step.Method.Name, step);

    public static void {verb}Async<TInput>(Func<dynamic, TInput, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(step.Method.Name, step);

    public static void {verb}Async<TContext, TInput>(Func<TContext, TInput, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(step.Method.Name, step);

    // ---

    public static void {verb}(string name, Action step) =>
        BehaviorBuilder.Current.{verb}(name, step);

    public static void {verb}(string name, Action<dynamic> step) =>
        BehaviorBuilder.Current.{verb}(name, step);

    public static void {verb}(string name, Action<dynamic, dynamic> step) =>
        BehaviorBuilder.Current.{verb}(name, step);

    public static void {verb}<TContext>(string name, Action<TContext> step) =>
        BehaviorBuilder.Current.{verb}(name, step);

    public static void {verb}<TInput>(string name, Action<dynamic, TInput> step) =>
        BehaviorBuilder.Current.{verb}(name, step);

    public static void {verb}<TContext, TInput>(string name, Action<TContext, TInput> step) =>
        BehaviorBuilder.Current.{verb}(name, step);

    // ---

    public static void {verb}Async(string name, Func<Task> step) =>
        BehaviorBuilder.Current.{verb}Async(name, step);

    public static void {verb}Async(string name, Func<dynamic, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(name, step);

    public static void {verb}Async(string name, Func<dynamic, dynamic, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(name, step);

    public static void {verb}Async<TContext>(string name, Func<TContext, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(name, step);

    public static void {verb}Async<TInput>(string name, Func<dynamic, TInput, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(name, step);

    public static void {verb}Async<TContext, TInput>(string name, Func<TContext, TInput, Task> step) =>
        BehaviorBuilder.Current.{verb}Async(name, step);

    // ---

    public static void {verb}<TStep>() where TStep : IStep, new() =>
        BehaviorBuilder.Current.{verb}(new TStep());

    public static void {verb}(IStep step)
    {{
        if(step is LambdaStep lambda)
        {{
            lambda.SetVerb(""{verb}"");
        }}

        BehaviorBuilder.Current.AddStep(step);
    }}

    //// ---

    //private static Behavior {verb}Internal(this Behavior behavior, string name, Delegate step)
    //{{
    //    behavior.AddStep(
    //        new {verb}LambdaStep()
    //            .SetName(name)
    //            .Handle(step));

    //    return behavior;
    //}}
}}
";
}
