using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;

namespace DrillSergeant.Generators;

[Generator, ExcludeFromCodeCoverage]
public class VerbGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Uncomment the following line to debug the generator.
        // System.Diagnostics.Debugger.Launch();

        var files = context.AdditionalTextsProvider.Where(t => new FileInfo(t.Path).Name.ToLower() == "verbdefinitions.txt");
        var providers = files.Select((text, token) => text.GetText(token)!.ToString());

        context.RegisterSourceOutput(providers, static (context, text) =>
        {
            foreach (var verbGroup in VerbDefinitionParser.Parse(text))
            {
                var ns = $"DrillSergeant.Syntax.{verbGroup.Name}";

                context.AddSource($"{verbGroup.Name}.g.cs", GetVerbGroupStaticsTemplateHeader("DrillSergeant", verbGroup.Name));

                foreach (var verb in verbGroup.Verbs)
                {
                    context.AddSource($"{verbGroup.Name}/Syntax/{verb}Step.g.cs", GetVerbStepTemplate(ns, verb));
                    context.AddSource($"{verbGroup.Name}/Syntax/{verb}LambdaStep.g.cs", GetLambdaVerbStepTemplate(ns, verb));
                    context.AddSource($"{verbGroup.Name}/Syntax/BehaviorExtensions.{verb}.g.cs", GetBehaviorExtensionsTemplate(ns, verb));

                    context.AddSource($"{verbGroup.Name}_{verb}.g.cs", GetVerbGroupStaticsTemplate("DrillSergeant", verbGroup.Name, verb));
                }
            }
        });
    }

    private static string GetVerbStepTemplate(string ns, string verb) => $@"
// <auto-generated />
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace {ns};

[ExcludeFromCodeCoverage]
public class {verb}Step : VerbStep
{{
    public {verb}Step()
    {{
    }}

    public {verb}Step(string? name)
        : base(name)
    {{
    }}

    public override string Verb => ""{verb}"";
}}";

    private static string GetLambdaVerbStepTemplate(string ns, string verb) => $@"
// <auto-generated />
using System.Diagnostics.CodeAnalysis;

namespace {ns};

[ExcludeFromCodeCoverage]
public class {verb}LambdaStep : LambdaStep
{{
    public {verb}LambdaStep()
    {{
        SetVerb(""{verb}"");
    }}

    public {verb}LambdaStep(string name)
        : base(name)
    {{
        SetVerb(""{verb}"");
    }}
}}
";

    private static string GetBehaviorExtensionsTemplate(string ns, string verb) => $@"
// <auto-generated />
using System.Diagnostics.CodeAnalysis;
using System;
using System.Threading.Tasks;

namespace {ns};

[ExcludeFromCodeCoverage]
public static partial class BehaviorExtensions_{verb}
{{
    public static Behavior {verb}(this Behavior behavior, Action step) =>
        behavior.{verb}(step.Method.Name, step);

    public static Behavior {verb}Async(this Behavior behavior, Func<Task> step) =>
        behavior.{verb}Internal(step.Method.Name, step);

    public static Behavior {verb}(this Behavior behavior, string name, Action step) =>
        behavior.{verb}Internal(name, step);

    public static Behavior {verb}Async(this Behavior behavior, string name, Func<Task> step) =>
        behavior.{verb}Internal(name, step);

    // ---

    public static Behavior {verb}<TStep>(this Behavior behavior) where TStep : IStep, new() =>
        behavior.{verb}(new TStep());

    public static Behavior {verb}(this Behavior behavior, IStep step)
    {{
        if(step is LambdaStep lambda)
        {{
            lambda.SetVerb(""{verb}"");
        }}

        behavior.AddStep(step);
        return behavior;
    }}

    // ---

    private static Behavior {verb}Internal(this Behavior behavior, string name, Delegate step)
    {{
        behavior.AddStep(
            new {verb}LambdaStep()
                .SetName(name)
                .Handle(step));

        return behavior;
    }}
}}
";


    private static string GetVerbGroupStaticsTemplateHeader(string ns, string groupName) => $@"
// <auto-generated />
using System.Diagnostics.CodeAnalysis;
using System;
using System.Threading.Tasks;

namespace {ns};

[ExcludeFromCodeCoverage]
public static partial class {groupName}
{{
}}
";


    private static string GetVerbGroupStaticsTemplate(string ns, string groupName, string verb) => $@"
// <auto-generated />
using System.Diagnostics.CodeAnalysis;
using System;
using System.Threading.Tasks;
using DrillSergeant.Syntax.{groupName};

namespace {ns};

public static partial class {groupName}
{{
    public static void {verb}(Action step) =>
        BehaviorBuilder.Current.{verb}(step.Method.Name, step);

    public static void {verb}Async(Func<Task> step) =>
        BehaviorBuilder.Current.{verb}Async(step.Method.Name, step);

    public static void {verb}(string name, Action step) =>
        BehaviorBuilder.Current.{verb}(name, step);

    public static void {verb}Async(string name, Func<Task> step) =>
        BehaviorBuilder.Current.{verb}Async(name, step);

    // ---

    public static void {verb}<TStep>() where TStep : IStep, new() =>
        BehaviorBuilder.Current.{verb}(new TStep());

    public static void {verb}(IStep step)
    {{
        if(step is LambdaStep lambda)
        {{
            lambda.SetVerb(""{verb}"");
        }}

        BehaviorBuilder.Current.AddStep(step);
    }}
}}
";
}
