name: calculate-versions

on:
  workflow_call:
    outputs:
      version:
        description: "The version for the assembly"
        value: ${{ jobs.calculate-variables.outputs.version }}
      package-version:
        description: "The version for the package"
        value: ${{ jobs.calculate-variables.outputs.package-version }}
      packages-directory:
        description: "The directory containing the nuget packages"
        value: ${{ github.workspace }}/packages
      should-deploy:
        description: "A boolean flag indicating whether "
        value: ${{ github.ref_type=='tag' || github.ref_name=='main' }}

env:
  DOTNET_NOLOGO: true

jobs:
  calculate-variables:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calculate-version.outputs.VERSION }}
      package-version: ${{ steps.calculate-version.outputs.PACKAGE_VERSION }}
      should-deploy: ${{ steps.check-for-deployment.outputs.SHOULD_DEPLOY }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Restore Packages
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Calculate Package Version
        id: calculate-version
        shell: pwsh
        run: |
          function saveOutput($name, $value) {
            echo "Saving output: $name=$value"
            echo "$name=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBom -Append
          }
          
          $packageVersion = if ($env:GitVersion_TagName) {
            $env:GitVersion_MajorMinorPatch + '-' + $env:GitVersion_TagName
          } else {
            $env:GitVersion_SemVer
          }
          
          saveOutput 'VERSION' $env:GitVersion_MajorMinorPatch
          saveOutput 'PACKAGE_VERSION' $packageVersion
