  name: calculate-version

  on:
    workflow_call:
      outputs:
        version: 
          description: "The version for the assembly"
          value: ${{ jobs.calculate-version.outputs.version }}
        package-version:
          description: "The version to use for packaging"
          value: ${{ jobs.calculate-version.outputs.semver }}

  jobs:
    calculate-version:
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.calculate-version.outputs.VERSION }}
        package-version: ${{ steps.calculate-version.outputs.PACKAGE_VERSION }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            show-progress: false
            fetch-depth: 0

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: |
              6.0.x

        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v0.10.2
          with:
            versionSpec: '5.x'

        - name: Get Current Version
          uses: gittools/actions/gitversion/execute@v0.10.2

        - name: Calculate New Version
          id: calculate-version
          shell: pwsh
          run: |
            function saveOutput($name, $value) {
              echo "Saving output: $name=$value"
              echo "$name=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBom -Append
            }
            
            $packageVersion = if ($env:GitVersion_TagName) {
              $env:GitVersion_MajorMinorPatch + '-' + $env:GitVersion_TagName
            } else {
              $env:GitVersion_SemVer
            }
            
            saveOutput 'VERSION' $env:GitVersion_MajorMinorPatch
            saveOutput 'PACKAGE_VERSION' $packageVersion
