name: push

on:
  workflow_call:
    inputs:
      packages-directory:
        description: "The directory to where the nuget packages are stored"
        type: "string"
        required: true

env:
  DOTNET_NOLOGO: true
  packages-directory: ${{ github.workspace }}/Artifacts/Packages

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Download Packages
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: ${{ inputs.packages-directory }}

      - name: List Packages
        shell: pwsh
        run: |
          Get-ChildItem -Path ${{ inputs.packages-directory }}

      - name: Push Packages
        if: false
        shell: pwsh
        env:
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
        run: |
          Get-ChildItem -Path ${{ inputs.packages-directory }} *.nupkg | ForEach-Object {
            $pushArgs = @(
              $_.FullName,
              '--source', '${{ env.NUGET_SOURCE }}',
              '--api-key', '${{ secrets.NUGET_API_KEY }}',
              '--skip-duplicate'
            )

            dotnet nuget push @pushArgs
          }
