name: build-packages

on:
  workflow_call:
    inputs:
      version:
        description: "The version type (major, minor, or patch)"
        required: true
        type: string

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/Artifacts/Packages
          key: ${{ runner.os }}-packages-${{ needs.calculate-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-packages-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Build and Test
        env:
          DOTNET_NOLOGO: true
          logger: GitHubActions;report-warnings=false
          packages-directory: ${{ github.workspace }}/Artifacts/Packages
          assembly-version: ${{ format('{0}.0', inputs.version) }}
          file-version: ${{ format('{0}.0', inputs.version) }}
        run: |
          dotnet restore
          dotnet build 
            --no-restore 
            --configuration Release 
            /property:ContinuousIntegrationBuild=true
          
          dotnet test 
            --no-restore 
            --no-build 
            --configuration Release 
            --logger:"${{ env.logger }}" 
            /property:AssemblyVersion=${{ env.assembly-version }} 
            /property:FileVersion=${{ env.file-version }}
          
          dotnet pack 
            --no-restore 
            --no-build 
            --include-symbols 
            --configuration Release 
            --output ${{ env.packages-directory }} 
            /property:Version=${{ inputs.version }}
