name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version type (major, minor, or patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ github.ref_name == 'main' && secrets.PUSH_KEY || github.token }}
          fetch-depth: 0
          
          #      - name: Setup Git
          #        run: |
          #          git config user.name 'Bitcobblers'
          #          git config user.email 'admin@bitcobblers.com'      
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'
      
      - name: Get Current Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        
      - name: Create New Tag
        run: |
          MAJOR=${{ inputs.version.options == 'major' && steps.gitversion.outputs.major + 1 ?? steps.gitversion.outputs.major }}
          MINOR=${{ inputs.version.options == 'minor' && steps.gitversion.outputs.minor + 1 ?? steps.gitversion.outputs.minor }}
          PATCH=${{ inputs.version.options == 'patch' && steps.gitversion.outputs.patch + 1 ?? steps.gitversion.outputs.patch }}
          TAG_NAME=v$MAJOR.$MINOR.$PATCH
          echo "New tagged version: $TAG_NAME"
          git tag $TAG_NAME
          git push origin $TAG_NAME --dry-run
