name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version type (major, minor, or patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ github.ref_name == 'main' && secrets.PUSH_KEY || github.token }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            7.0.x

      - name: Restore Tools
        run: |
          dotnet tool restore

      - name: Setup Git
        run: |
          git config user.name 'Bitcobblers'
          git config user.email 'admin@bitcobblers.com'

      - name: Bump Version
        run: |
          nbgv prepare-release --versionIncrement ${{ github.event.inputs.version }}
