name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version type (major, minor, or patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DS_PUSH_KEY }}
          show-progress: false
          fetch-depth: 0
          
          #      - name: Setup Git
          #        run: |
          #          git config user.name 'Bitcobblers'
          #          git config user.email 'admin@bitcobblers.com'      
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'
      
      - name: Get Current Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        
      - name: Create New Tag
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.DS_PUSH_KEY }}
        run: |
          function inc($comp, $value) { 
            if($comp -eq '${{ inputs.version }}') {
              return $value + 1
            }
            else {
              return $value
            }
          }

          $Major = inc 'major' $env:GitVersion_Major
          $Minor = inc 'minor' $env:GitVersion_Minor
          $Patch = inc 'patch' $env:GitVersion_Patch
          $TagName = "v$Major.$Minor.$Patch"

          Write-Output "New tagged version: $TagName"
          & git tag $TagName
          & git push origin $TagName --dry-run
