name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version type (major, minor, or patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - none

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name 'Bitcobblers'
          git config user.email 'admin@bitcobblers.com'      
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'
      
      - name: Get Current Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        
      - name: Create New Tag
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.DS_PUSH_KEY }}
        run: |
          function bumpVersion($comp, $value) { 
            if($comp -eq '${{ inputs.version }}') {
              return [int]$value + 1
            }
            else {
              return $value
            }
          }
          
          $Major = bumpVersion 'major' $env:GitVersion_Major
          $Minor = bumpVersion 'minor' $env:GitVersion_Minor
          $Patch = bumpVersion 'patch' $env:GitVersion_Patch

          $OldVersion = "$env:GitVersion_Major.$env:GitVersion_Minor.$env:GitVersion_Patch"
          $NewVersion = "$Major.$Minor.$Patch"
          $TagName = "v$NewVersion"

          Write-Output "New tagged version: $TagName"
          & git tag -a $TagName -m "Bumped $OldVersion to $NewVersion"
          & git push origin $TagName
