name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:
            6.0.x
            7.0.x

      - name: Publish to Nuget
        run: ./build.sh Publish
        env:
          Configuration: Release
          NuGetApiKey: ${{ secrets.NUGET_API_KEY }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
