name: CICD
on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_call:
  workflow_dispatch:
    inputs:
      run-codeql:
        description: "Run CodeQL analysis"
        required: false
        default: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref_name }}"

  codeql:
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.run-codeql) ||
      (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev'))
    uses: ./.github/workflows/codeql.yml
