name: CICD
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  codeql:
    uses: ./.github/workflows/_codeql.yml

  calculate-version:
    uses: ./.github/workflows/_calculate-version.yml

  build-packages:
    needs: [ calculate-version ]
    uses: ./.github/workflows/_build-packages.yml
    with:
      version: ${{ needs.calculate-version.outputs.version }}
      semver: ${{ needs.calculate-version.outputs.semver }}

  push-packages:
    if: github.tag_name != '' || github.ref_name == 'dev'
    needs: [ test, calculate-version, build-packages, codeql ]
    uses: ./.github/workflows/_push-packages.yml
    with:
      version: ${{ needs.calculate-version.outputs.semver }}
    secrets: inherit

  create-release:
    if: github.tag_name != '' && github.ref_name == 'main'
    needs: [push-packages, calculate-version]
    uses: ./.github/workflows/_create-release.yml
    with:
      version: ${{ needs.calculate-version.outputs.version }}
      tag-name: ${{ github.tag_name }}
