name: CICD
on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref_name }}"

  codeql:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev'))
    uses: ./.github/workflows/codeql.yml
