name: CICD
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/_test.yml
    secrets: inherit

  codeql:
    if: github.ref_type == 'tag' || github.ref_name == 'dev' || github.ref_name == 'main'
    uses: ./.github/workflows/_codeql.yml

  check-tag:
    uses: ./.github/workflows/_check-tag.yml

  deploy:
    if: github.ref_type == 'tag' || github.ref_name == 'dev'
    needs: [ test, codeql ]
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit

  create-release:
    if: needs.check-tag.outputs.has-release-tag == 'true'
    needs: [deploy, check-tag]
    uses: ./.github/workflows/_create-release.yml
    with:
      version: ${{ needs.deploy.outputs.version }}
      tag-name: ${{ github.ref_name }}
