name: CICD
on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_call:
  workflow_dispatch:
    inputs:
      run-codeql:
        description: "Run CodeQL analysis"
        required: false
        default: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  codeql:
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.run-codeql) ||
      (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev'))
    uses: ./.github/workflows/codeql.yml
