name: CICD
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/_test.yml
    secrets: inherit

  codeql:
    if: github.tag_name != '' || github.ref_name == 'dev'
    uses: ./.github/workflows/_codeql.yml

  deploy:
    # if: github.tag_name != '' || github.ref_name == 'dev'
    needs: [ test, codeql, docfx ]
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit

  docfx:
    uses: ./.github/workflows/_docfx.yml
    secrets: inherit

  create-release:
    if: github.tag_name != '' && github.ref_name == 'main'
    needs: [deploy]
    uses: ./.github/workflows/_create-release.yml
    with:
      version: ${{ needs.deploy.outputs.version }}
      tag-name: ${{ github.tag_name }}
