name: push-packages

on:
  workflow_call:
    inputs:
      version:
        description: "The version type (major, minor, or patch)"
        required: true
        type: string

jobs:
  push-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Packages
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/Artifacts/Packages
          key: ${{ runner.os }}-packages-${{ inputs.version }}
          lookup-only: true
          fail-on-cache-miss: true
          restore-keys: |
            ${{ runner.os }}-packages-

      - name: Push Packages
        env:
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          package-glob: ${{ github.workspace }}/Artifacts/Packages/*.nupkg
        run: |
          for FILE in ${{ env.package-glob }}; do
            echo "Pushing package: $FILE";
          done