name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version type (major, minor, or patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - none
      run-codeql:
        description: "Run CodeQL analysis"
        required: false
        type: boolean
        default: false

jobs:
  cicd:
    uses: ./.github/workflows/cicd.yml
    with:
      run-codeql: ${{ inputs.run-codeql }}
    secrets: inherit

  calculate-version:
    uses: ./.github/workflows/_calculate-version.yml
    with:
      version: ${{ inputs.version }}

  build-packages:
    needs: [ calculate-version ]
    uses: ./.github/workflows/_build-packages.yml
    with:
      version: ${{ needs.calculate-version.outputs.version }}

  create-tags:
    needs: [ calculate-version, build-packages, cicd ]
    uses: ./.github/workflows/_create-tags.yml
    with:
      tag-name: ${{ needs.calculate-version.outputs.tag-name }}

  push-packages:
    needs: [ build-packages, create-tags ]
    uses: ./.github/workflows/_push-packages.yml
    with:
      version: ${{ needs.calculate-version.outputs.version }}
    secrets: inherit

  create-release:
    needs: [calculate-version, push-packages]
    uses: ./.github/workflows/_create-release.yml
    with:
      version: ${{ needs.calculate-version.outputs.version }}
      tag-name: ${{ needs.calculate-version.outputs.tag-name }}
